name: Publish Docker image
on:
  push:
    branches: [ enable_multiarch_build ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Build linux/arm64
        run: docker buildx build --push --platform linux/arm64 -t luxonis/depthai-library:${{ steps.vars.outputs.short_ref }} -f ci/Dockerfile .
      - name: linux/amd64
        run: docker buildx build --push --platform linux/amd64 -t luxonis/depthai-library:${{ steps.vars.outputs.short_ref }} -f ci/Dockerfile .
      - name: linux/arm/v7
        run: docker buildx build --push --platform linux/arm/v7 -t luxonis/depthai-library:${{ steps.vars.outputs.short_ref }} -f ci/Dockerfile .
