name: Publish Docker image
on:
  push:
    tags:
      - "*"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build and push
        run: |
          docker buildx build --push --platform linux/arm64,linux/amd64,linux/arm/v7 -t luxonis/depthai-library:${{ steps.vars.outputs.short_ref }} -f ci/Dockerfile .